### ISSUE TITLE
[Feature]: LSP

### ISSUE THREAD

**Issue by abarbu** [tweag/jupyterWith#402]
### What's missing?

Jupyter LSP support has two components. A frontend component and a server component, jupyter-lsp.

I have tried, but I cannot get jupyter-lsp to load up in a server created by jupyterWith; even if I do something hacky to get the frontend component loaded up.

What's the right way to get LSP working?

**Comment by djacu** [comment]
Hey @abarbu 

What have you tried so far.

I tried to setup a kernel real quick and ran into some issues. Here is what I did.

1. Followed the Quick Start on the docs site to pull down the template. https://jupyterwith.tweag.io/getting-started/
2. Created a new folder `my-project/kernels/custom-python` for the new kernel.
3. Created a `default.nix` file in there with the following.
```nix
{
  name,
  availableKernels,
  extraArgs,
}:
availableKernels.python {
  projectDir = ./.;
  displayName = "Python with jupyterlab-lsp";
  name = "python-with-jupyterlab-lsp";
}
```
4. Created a `pyproject.toml` file with the following.
```toml
[tool.poetry]
name = "jupyter-nix-kernel-ipython"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
ipykernel = "^6.15.0"
jupyterlab-lsp = "^3.10.2"
python-lsp-server = {extras = ["all"], version = "^1.7.0"}

[tool.poetry.dev-dependencies]
# build systems for dependencies
hatchling = "^1.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
5. lock the dependencies with `poetry lock`
6. Run `nix run` at the top level.

However, after I tried that I ran into an infinite recursion error similar to https://github.com/nix-community/poetry2nix/issues/750.
I tried adding some overrides but that created new problems.
