### ISSUE TITLE
[Bug]: Using any `poetry` based kernel fails (unable to find `ipykernel`)

### ISSUE THREAD

**Issue by quantum9Innovation** [tweag/jupyterWith#568]
### Current Behavior

Even though I've specifyed `ipykernel` as a dependency and verified that it exists in `poetry.lock`, I get an error saying the kernel is unable to find module `ipykernel_launcher`, which causes the kernel to be restarted multiple times before ultimately failing.

This is the `pyproject.toml` I'm using (in `kernel` directory):

```toml
[tool.poetry]
name = "jupyter-nix-kernel"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.12"
vpython = "^7.6.5"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
```

For context, here is my `kernels.nix`:

```nix
_: {
  kernel.python.kernel.enable = true;
  kernel.python.kernel.projectDir = ./kernel;
}
```

and `flake.nix`:

```nix
{
  description = "ES.8022 Jupyter notebook";

  nixConfig.extra-substituters = [
    "https://tweag-jupyter.cachix.org"
  ];
  nixConfig.extra-trusted-public-keys = [
    "tweag-jupyter.cachix.org-1:UtNH4Zs6hVUFpFBTLaA4ejYavPo5EFFqgd7G7FxGW9g="
  ];

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    jupyenv.url = "github:tweag/jupyenv";
    pre-commit-hooks.url = "github:cachix/git-hooks.nix";
  };

  outputs =
    {
      self,
      flake-utils,
      nixpkgs,
      jupyenv,
      pre-commit-hooks,
      ...
    }:
    flake-utils.lib.eachSystem
      [
        flake-utils.lib.system.x86_64-linux
      ]
      (
        system:
        let
          inherit (jupyenv.lib.${system}) mkJupyterlabNew;
          jupyterlab = mkJupyterlabNew (
            { ... }:
            {
              inherit nixpkgs;
              imports = [ (import ./kernels.nix) ];
            }
          );
          pkgs = nixpkgs.legacyPackages.${system};
        in
        {
          checks = {
            pre-commit-check = pre-commit-hooks.lib.${system}.run {
              src = ./.;
              hooks = {
                nixfmt-rfc-style.enable = true;
                // ...
              };
            };
          };
          packages = {
            inherit jupyterlab;
          };
          packages.default = jupyterlab;
          devShells.default = pkgs.mkShell {
            name = "launcher";
            inherit (self.checks.${system}.pre-commit-check) shellHook;
            buildInputs = self.checks.${system}.pre-commit-check.enabledPackages;
            packages = with pkgs; [ poetry ];
          };
          apps.default.program = "${jupyterlab}/bin/jupyter-lab";
          apps.default.type = "app";
          formatter = pkgs.nixfmt-rfc-style;
        }
      );
}
```

### Expected Behavior

The kernel should already have `ipykernel` installed and should work fine (I've tested `python-scientific`, for example, and this works without a problem, but the `python-with-numpy` example fails because it uses a Poetry environment)

### Steps To Reproduce

1. See `flake.nix`, `kernels.nix`, and `pyproject.toml` files in issue description
2. Place `pyproject.toml` in `kernel` directory and other files in root directory
3. Run `poetry lock` in `kernel` directory
4. Run `nix run` from root directory

### OS

```shell
- system: `"x86_64-linux"`
 - host os: `Linux 6.12.2-zen1, NixOS, 25.05 (Warbler), 25.05.20250108.bffc22e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/nix/store/v0g0bxsd5gw6k0jz2855f8h7l1218925-source`
```

### Version

latest (github:tweag/jupyenv)

### Relevant log output

```shell
/nix/store/sjdq516c6cdaf81nrgx32gbxkh6sdbpw-python3-3.12.7-env/bin/python3.12: No module named ipykernel_launcher
[I 2025-02-03 22:51:53.669 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
/nix/store/sjdq516c6cdaf81nrgx32gbxkh6sdbpw-python3-3.12.7-env/bin/python3.12: No module named ipykernel_launcher
[W 2025-02-03 22:51:56.684 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2025-02-03 22:51:56.684 ServerApp] Kernel ca572a52-db2b-404b-8a16-cdbb958bdad7 died, removing from map.
[W 2025-02-03 22:51:58.821 ServerApp] 404 GET /api/kernels/ca572a52-db2b-404b-8a16-cdbb958bdad7?1738641118814 (127.0.0.1): Kernel does not exist: ca572a52-db2b-404b-8a16-cdbb958bdad7
```

**Comment by anpin** [comment]
I think ipykernel should be in the [tool.poetry.dev-dependencies] not [tool.poetry.dependencies]
```toml
[tool.poetry]
name = "jupyter-nix-kernel"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.12"
vpython = "*"

[tool.poetry.dev-dependencies]
ipykernel = ""

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
```

EDIT: verified that this fixes the issue in your repro

**Comment by quantum9Innovation** [comment]
I'm able to use the kernel now, but I can't access any packages declared in `pyproject.toml`. Here is my updated `pyproject.toml`:

```toml
[tool.poetry]
name = "jupyter-nix-kernel"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.12"
# vpython = "^7.6.5"
numpy = "^2.2.3"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
```

Running a cell with `import numpy as np` errors saying `numpy` is not found, even after I update `poetry.lock` and `flake.nix`.
